#!/bin/bash

# optional depth argument, defaults to 20
depth=${1:-20}

xclip -selection clipboard -out \
    | checkplus -d $depth \
    | gnuplot -p -e "set title \"Depth = $depth\"; unset key; plot '-' with lines"
